[debug] [2022-08-12T09:16:01.872Z] ----------------------------------------------------------------------
[debug] [2022-08-12T09:16:01.874Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\eKasi_TMB_COM00710\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy --only hosting
[debug] [2022-08-12T09:16:01.874Z] CLI Version:   11.6.0
[debug] [2022-08-12T09:16:01.874Z] Platform:      win32
[debug] [2022-08-12T09:16:01.874Z] Node Version:  v16.15.1
[debug] [2022-08-12T09:16:01.877Z] Time:          Fri Aug 12 2022 11:16:01 GMT+0200 (South Africa Standard Time)
[debug] [2022-08-12T09:16:01.877Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-08-12T09:16:01.945Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-08-12T09:16:01.945Z] > authorizing via signed-in user (msenyanyathi33@gmail.com)
[debug] [2022-08-12T09:16:01.945Z] [iam] checking project covidapp-d862e for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2022-08-12T09:16:01.947Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/covidapp-d862e:testIamPermissions [none]
[debug] [2022-08-12T09:16:01.948Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/covidapp-d862e:testIamPermissions x-goog-quota-user=projects/covidapp-d862e
[debug] [2022-08-12T09:16:01.948Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/covidapp-d862e:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2022-08-12T09:16:13.889Z] [iam] error while checking permissions, command may fail: FirebaseError: Failed to make request to https://cloudresourcemanager.googleapis.com/v1/projects/covidapp-d862e:testIamPermissions
[debug] [2022-08-12T09:16:13.892Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/covidapp-d862e [none]
[debug] [2022-08-12T09:16:25.856Z] Failed to make request to https://firebase.googleapis.com/v1beta1/projects/covidapp-d862e
[debug] [2022-08-12T09:16:30.881Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\eKasi_TMB_COM00710\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:253:49)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[error] 
[error] Error: An unexpected error has occurred.
